version: '3'
services:
  sync:
    container_name: sync
    image: syncthing/syncthing:latest
    ports:
      - 8086:8384
      - 22000:22000
    volumes:
      - syncthing-data:/var/syncthing
      - /mnt/documents/Sync:/data/Sync
      - /mnt/documents/Dotfiles:/data/Dotfiles
      - /mnt/pictures/Camera:/data/Camera
    hostname: pi.local
    restart: unless-stopped

volumes:
    syncthing-data:
