version: '3'

services:
  glances:
    image: nicolargo/glances:dev
    restart: unless-stopped
    container_name: glances
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - 8091:61208
        - 8092:61209
    environment:
      - "GLANCES_OPT=-w"
    pid: host
