version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - proxynet
    env_file:
      - ~/.env
    restart: unless-stopped

networks:
  proxynet:
volumes:
  postgres-data:
