- hosts: all
  become: yes
  become_user: root
  tasks:
    - hostname: name=enceladus
    - apt:
        name:
          - git
          - mosh
          - tmux
          - python3-pip
          - python3-venv
          - htop
          - vim
          - logrotate
          - nfs-common
          - ncdu
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - libssl-dev
          - zsh
    - pip:
        name:
          - virtualenv
          - pip
          - pipx
        state: latest
    - name: Logrotate config
      copy:
        dest: /etc/logrotate.d/ansible-pull
        content: |
          /var/log/ansible-pull.log {
            rotate 7
            daily
            compress
            missingok
            notifempty
          }
    - name: Set authorized keys
      authorized_key:
        state: present
        user: pi
        key: https://github.com/histrio.keys
    - timezone: name=Europe/Podgorica
    - systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
    - user:
        name: "pi"
        shell: /bin/bash

- hosts: all
  become: yes
  become_user: pi
  tasks:
    - name: Install oh-my-tmux
      git:
        repo: https://github.com/gpakosz/.tmux.git
        dest: ~/.tmux/
        depth: 1
    - file:
        src: ~/.tmux/{{ item }}
        dest: ~/{{ item }}
        state: link
      with_items:
        - .tmux.conf
        - .tmux.conf.local
    - name: Install powerline fonts
      git:
        repo: https://github.com/powerline/fonts.git
        dest: /tmp/fonts
        depth: 1
    - command:
        cmd: bash /tmp/fonts/install.sh
    - name: Install python binaries
      command:
        cmd: /usr/local/bin/pipx install {{ item.name }}
        creates: ~/.local/bin/{{ item.bin | default(item.name) }}
      with_items:
        - {name: awscli, bin: aws}
        - {name: ansible-base, bin: ansible}
        - {name: git-review}
    - name: Install Rust
      shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"

