---
version: "3"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre
    volumes:
      - calibre-data:/config
      - /mnt/documents/0.shelf/:/books:ro
    ports:
      - 8083:8083
    restart: unless-stopped

volumes:
  calibre-data:
