version: '2'

services:
  sickchill:
    image: sickchill/sickchill:latest
    container_name: sickchill
    restart: unless-stopped
    ports:
      - 8085:8081
    volumes:
      - sickchill-data:/data
      - /mnt/downloads/serials/:/downloads:ro
      - sickchill-tv:/tv
      - sickchill-cache:/app/sickchill/sickchill/gui/slick/cache
      - /etc/localtime:/etc/localtime:ro


volumes:
    sickchill-data:
    sickchill-downloads:
    sickchill-tv:
    sickchill-cache:
