version: '3'
services:
  todo:
      image: histrio/mytinytodo:latest
      container_name: todo
      ports:
        - "8096:80"
      volumes:
        - todo-data:/var/www/html/db
        - ./favicon.ico:/var/www/html/favicon.ico
      env_file:
        - ~/.env
      restart: unless-stopped
volumes:
  todo-data:
