version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "8090:443/tcp"
    env_file:
      - ~/.env
    volumes:
      - 'etc-pihole:/etc/pihole/'
      - 'etc-dnsmasq:/etc/dnsmasq.d/'
    restart: unless-stopped
    dns: 
      - 1.1.1.1
      - 8.8.8.8

volumes:
    etc-pihole:
    etc-dnsmasq:
