[tool.poetry]
name = "tdinbox"
version = "0.1.0"
description = ""
authors = ["Rinat Sabitov <rinat.sabitov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
