version: '3'
services:
  couchdb:
      image: couchdb:latest
      container_name: couchdb
      ports:
        - 5984:5984
      volumes:
        - couchdb-config:/opt/couchdb/etc/local.d/
        - couchdb-data:/opt/couchdb/data
      env_file:
        - ~/.env
      restart: unless-stopped
volumes:
  couchdb-config:
  couchdb-data:
